server:
  port: 8085
spring:
  data:
    mongodb:
      auto-index-creation: true
      database: publication
      host: localhost
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin